### PR TITLE
[wpmlbridge-63]

### PR DESCRIPTION
**Pull request by strategio**
The most important commit in this MR is the second one 7f64d3079d4843c18baf5977d31e615d7a8b4617 which is rewriting the tests for `WPML_MU_Domain_Mapping_Filters` .

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlbridge-63

### CODE REVIEW

**Review by andreasciamanna — CHANGES_REQUESTED** [review]
@strategio once again, this MR is impossible to review.

Is not something you don't know: files renaming or moving should have their own commit, so we can compare the changes.

**Comment by strategio** [comment]
@sciamannikoo, I removed the files in the first commit. Please review only the second one.

**Review by andreasciamanna — APPROVED** [review]
Fine to me

**Comment by brucepearson** [comment]
This looks ok. +1

**Pull request merged**
